name: Hello World Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: goodbye world
              run: echo "Hello World"
              shell: bash