name: Create new project.

on:
  workflow_dispatch:
    inputs:
        projectName:
            required: true
            default: 'Project X'
        projectCode:
            required: true
            default: 'prj-x-rn'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo '${{ toJson(github.event.inputs) }}'
              shell: bash