name: Create new project.

on:
  workflow_dispatch:
    inputs:
        projectName:
            required: true
            default: 'Project X'
        projectCode:
            required: true
            default: 'prj-x-rn'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-go@v1
          with:
            go-version: '1.14.6'
        - run: cd src && go mod vendor
        - name: create-json
          id: create-json
          uses: jsdaniell/create-json@v1.2.2
          with:
            name: "renative.json"
            json: ${{ secrets.SECRETS_TEST }}
            dir: "src/"