name: Creating new Flavour.

on:
  workflow_dispatch:
    inputs:
        enviroment:
            description: 'The enviroment to deploy to'
            required: true
            default: 'production'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying to ${{ github.event.inputs.enviroment }}"